[package]
name = "lipl"
version = "0.1.0"
authors = ["robin <yxdunc@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
tui = "0.6.2"
# cmd_lib = "0.7.8"
cmd_lib = { git = "https://github.com/yxdunc/rust_cmd_lib", rev = "b03088c253a7cd81e3f2dfda2db12702d7dc89c1" }
