name: Tests_OSX

on: [push]

jobs:
  build:

    runs-on: macos

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
      - uses: actions-rs/toolchain@master
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
